name: ci-master
on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  tag-statistics-image:
    name: "Tag the statistics image on ECR with the master commit hash"
    if: github.base_ref == 'master' && github.event.action == 'closed' && github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials if this is a PR close
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_TOOLING_PUSHECR }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_TOOLING_PUSHECR }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: "Get tag of source image"
        id: get-src-tag
        run: |
          echo "::set-output name=srctag::${{ github.event.pull_request.head.sha }}"
          
      - name: "Pull image from ECR, tag it and push it"
        run: |
          aws ecr get-login-password | docker login --username AWS --password-stdin ${{ secrets.ECR_REPO_HOST }}
          docker pull ${{ secrets.ECR_REPO_HOST }}/${{ secrets.ECR_REPO_NAME }}:${{ steps.get-src-tag.outputs.srctag }}
          docker tag ${{ secrets.ECR_REPO_HOST }}/${{ secrets.ECR_REPO_NAME }}:${{ steps.get-src-tag.outputs.srctag }} ${{ secrets.ECR_REPO_HOST }}/${{ secrets.ECR_REPO_NAME }}:${GITHUB_SHA}
          docker push ${{ secrets.ECR_REPO_HOST }}/${{ secrets.ECR_REPO_NAME }}:${GITHUB_SHA}

  deploy-stg-statistics:
    name: "Deploy the external statistics service to the stg environment"
    runs-on: ubuntu-latest
    if: github.base_ref == 'master' && github.event.action == 'closed' && github.event.pull_request.merged
    needs:
      - tag-statistics-image
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_STG_PUSHECR }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_STG_PUSHECR }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Retrieve Task Definition for external service on STG
        run: |
          aws ecs describe-task-definition --task-definition ${{ secrets.ECS_TASK_FAMILY_STG }} --query taskDefinition > task-definition.json
      - name: Show task definition
        run: |
          cat task-definition.json
      - name: Set image name as output
        id: set-image-output
        run: |
          echo "::set-output name=image::${{ secrets.ECR_REPO_HOST }}/${{ secrets.ECR_REPO_NAME }}:${GITHUB_SHA}"
      - name: Update Task Definition for STG with new image
        id: render-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: "${{ secrets.ECS_CONTAINER_NAME_STG }}"
          image: "${{ steps.set-image-output.outputs.image }}"
        env:
          IMAGE: "${{ secrets.ECR_REPO_HOST }}/${{ secrets.ECR_REPO_NAME }}:${GITHUB_SHA}"
      - name: Deploy new task definition
        id: deploy-task-definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.render-task-def.outputs.task-definition }}
          wait-for-service-stability: false
      - name: Determine scheduled task name
        id: get-scheduled-task-name
        run: |
          SCHEDULEDTASKNAME=$(aws events list-rules --query "Rules[*]|[?contains(Name,'Statist')].Name" --output text)
          echo "::set-output name=scheduledtaskname::${SCHEDULEDTASKNAME}"
      - name: Create new target config for the statistics scheduled task
        id: update-scheduled-task-statistics
        run: |
          aws events list-targets-by-rule --rule "${{ steps.get-scheduled-task-name.outputs.scheduledtaskname }}" > targetdef.orig.json
          jq '.Targets[0].EcsParameters.TaskDefinitionArn = "${{ steps.deploy-task-definition.outputs.task-definition-arn }}"' targetdef.orig.json > targetdef.json
          aws events put-targets --cli-input-json file://targetdef.json --rule "${{ steps.get-scheduled-task-name.outputs.scheduledtaskname }}"
